name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repohttps
          uses: actions/checkout@v4
          
        - name: List and read file
          run:  |
            echo "My First GitHub Actions Job"
            ls  -ltr
            cat README.md 
#          run: echo "My First GitHub Actions Job"

#       - name: List files
#          run: ls

#       - name: Read file
#          run: cat README.md